Repository jidone7061/mywebclass-simulation, pull requests merged in 2023-03, with the labels that each got.

#9 added Project link into development branch after merge with master
  readme.md
Labels: enhancement

#22 added google analytics script to index.html, content.html, story.html…
  src/content.html
  src/index.html
  src/privacy.html
  src/story.html
  src/templates/template-content.html
Labels: Improvement

#41 add link to Project Setup Instructions closes #40
  readme.md
Labels: documentation
